<?php
/**
 * Implements hook_help().
 */

function frankly_video_comment_help($path, $arg) {
  if ($path == 'admin/help#frankly_video_comment') {
    return t('A demonstration frankly_video_comment.');
  }
}

/********************************************* BLOCK MODULE ************************************************/

function frankly_video_comment_block_info() {

  $blocks['frankly_video_comment_block'] = array(
    'info' => t('Frankly Video Comment'),
    // DRUPAL_CACHE_PER_ROLE will be assumed.
  );

  return $blocks;
}



function frankly_video_comment_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();
  $block['content']='<div class="franklywidget" data-user="" data-widget="videoComment" data-query="" data-height="40" data-width="240" style="margin: auto"><a href="https://frankly.me">Frankly.me</a></div>

              <div class="franklywidget" data-user="" data-widget="viewComment" data-query="" data-height="340" data-width="100%" style="margin: auto"><a href="https://frankly.me">Frankly.me</a></div>

              <script src="https://frankly.me/js/franklywidgets.js"> </script> ';


  return $block;
}
